name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # steps:
    #   - name: checkout
    #     uses: actions/checkout@v2

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 5.161.104.141 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa root@5.161.104.141 'bash -s' < /var/www/testing-repo/deploy.sh
