name: Deploy

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Run deployment script
        run: ssh -o StrictHostKeyChecking=no root@5.161.104.141 'bash -s' < /var/www/testing-repo/deploy.sh
